### PR TITLE
Add Locale param

### PR DESCRIPTION
**Pull request by WXRIW**
There are lots of requests that support locale param. Sometimes this param is pretty useful.

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Hi!

Thanks for the contribution and work, awesome! :)

Do you have any documentation for the locale parameter?
e.g https://developer.spotify.com/documentation/web-api/reference/#/operations/get-an-artist doesnt list this parameter at all...or did they just forget to add it?

**Comment by WXRIW** [comment]
For most calls in Spotify Web API documentation, locale is not listed, but this parametric just works, such as "Get Artist", some artists' names are different in different locales.

**Comment by WXRIW** [comment]
I found that some API calls currently does not support locale param.  
Such as https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-top-artists-and-tracks  
I have posted this on [Spotify Developer Community](https://community.spotify.com/t5/Spotify-for-Developers/Some-API-calls-currently-don-t-support-quot-locale-quot-param/td-p/5467514).
Waiting for Spotify's reply.

**Comment by WXRIW** [comment]
I found that some API calls currently does not support locale param.  
Such as https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-top-artists-and-tracks  
I have posted this on [Spotify Developer Community](https://community.spotify.com/t5/Spotify-for-Developers/Some-API-calls-currently-don-t-support-quot-locale-quot-param/td-p/5467514).
Waiting for Spotify's reply.

**Comment by WXRIW** [comment]
For now I only found this call with locale param will return a 400 error.
https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-top-artists-and-tracks

**Comment by JohnnyCrazy** [comment]
Sorry for the delay here.

Although they're not officially documented, I still want to support them, so just merged it. Will be part of the next release tho, forgot to include it in this one.

**Comment by WXRIW** [comment]
> For now I only found this call with locale param will return a 400 error. https://developer.spotify.com/documentation/web-api/reference/#/operations/get-users-top-artists-and-tracks

This has been fixed by Spotify, so it's working now :)

**Pull request merged**
