### PR TITLE
Split API project into two (Local & Web)

### PR DESCRIPTION
**Pull request by petrroll**
I've split the API project into two separate projects for better maintainability and potential port of WebAPI to .NET Core. 

Specifically I've created a new project, copied WebAPI related stuff there, renamed the original, and had some fun with configuring Dependencies.

I've also updated Newtonsoft.Json dependencies to latest stable version.

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
I already thought about this split for a while now, and I think the benefits prevail. 

Although there is some more work behind the scenes:
* Will we create different releases for each lib?
* Guess we need to seperate NuGet Packages from now on, `SpotifyAPI-NET.Local` and `SpotifyAPI-NET,Web`?

I also thought about splitting the whole repo apart, but I don't think this would be good, creates a lot of confusion.

**Comment by petrroll** [comment]
At first I also thought about proposing splitting the whole repo instead of just project but then I realized there's little benefit to it, is actually quite a lot of work, and doesn't really help anything.

Regarding NuGet: IIRC having two separate packages is kinda necessary if you want to have two different sets of dependencies in NuGet (which you want if you ever want .NET core ready Web API), so yes :).

**Comment by JohnnyCrazy** [comment]
Mh, still, then there would be the problem with releases (git tags) together with NuGet versions...

**Comment by petrroll** [comment]
Hm, there're two ways to deal with that (at least two I can think of :) ).

1) GitHub releases don't have to be 1:1 with NuGet releases so you could just start creating two sets of releases. E.g. Local_2.11.0, Web_2.12.0, ...

2) Always update both releases even if one branch doesn't advance and version them together.

3) Or you could split up the repo...

---
I'd personally be for 1) but honestly have no experience with such problems :).

**Comment by JohnnyCrazy** [comment]
This PR will be merged later on, I'm still unsure how we should handle releases etc.

While I think 1) could work, it would be confusing having multiple releases in GitHub (e.g `Latest Release` would point to either a `Local`-Release or a `Web`-Release).

A .NET Core port is not #1 priority right now, so I think we have some time here.

**Comment by JohnnyCrazy** [comment]
I got some `good` news :)

I ran some tests on my arch machine today, and it seems like the linux client also supports the local API! (Why didn't I check this earlier?)
img

The good thing: We don't need to split the projects now, we can keep everything together mostly (except for the WindowsAPI Audio stuff, we will have to remove it propably).

The bad thing: Now we have to port `2` libraries :stuck_out_tongue_winking_eye: 

So I will go get some reading on how to make .NET Core Projects and report back.

**Comment by petrroll** [comment]
I don't know, I'd still be for splitting up the project...

1) The online part is officially supported while the local one isn't 

2) The library might be useful even for non-client deployments e.g. for some server service

3) Those two parts are already quite separated in the code

Thinking about it, is there any problem with approach 2) -> versioning and releasing both releases together?

**Comment by JohnnyCrazy** [comment]
Mh, but those arguments are too weak to make this huge step IMO:
* 1) While it's true, what difference does it make? Spotify doesn't discourage the use of it, so it should be fine keeping them together. (They even added this wrapper to the list of supported Web API wrappers)
* 2) The LocalAPI code has a very low amount of LOC and since both will rely on the same dependencies after the update, every server can run the library without having to use the local api.
* 3) Yes, because I wanted to have them clearly seperated, but still be able to use them easily together. Most (/every) devs want to keep their dependencies low, splitting them up adds another DLL for a very tiny amount of code.

2) is very hacky IMO. It feels wrong realeasing a new version (on nuget e.g) without changing anything. This would brake the whole point of versioning. Still, if you just would release the specific branch if there are changes in the version, you would end up with jumping version numbers --> even more confusing

**Comment by petrroll** [comment]
Alright, I see your point now :). 
I suppose you can close this PR then.

**Comment by JohnnyCrazy** [comment]
Alright, I guess we can use #64 for some further discussion about porting it over.

Thanks for your input, I really appreciate it! :)

**Pull request closed without merging**
