### PR TITLE
Implementing 'Play URL' function

### PR DESCRIPTION
**Pull request by Nekonime**

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Hi, 

So what is this change for? Anything was not working before?

**Comment by Nekonime** [comment]
The 'PlayURL' button only seems to tell Spotify to play "Right Down The Line" by Gerry Rafferty. I have no idea why, so I made this little workaround.

**Comment by JohnnyCrazy** [comment]
Make sure you empty the context first, which is below the PlayURL field:
img

**Comment by Nekonime** [comment]
Didn't think those two boxes had anything to do with each other. Sorry about that >_<

**Comment by JohnnyCrazy** [comment]
No Problem :)
Context was just added with the last commits, Maybe I will add a note once I pushed the rewrite

**Pull request closed without merging**
