### PR TITLE
Fixed issues #926, and #928.

### PR DESCRIPTION
**Pull request by Lewis-Fam**
Added a double to int Json Converter and added attributes to impacted properties.

### CODE REVIEW

**Comment by munissor** [comment]
FWIW, I like this approach, will fix the serialization issue in a non-breaking way. The public API will keep integers until we can figure out if the change from Spotify is intentional or not.

**Comment by Lewis-Fam** [comment]
There are a few ways to handle the failing check.

Either, update the attribute tag to: 
`[JsonConverter(typeof(DoubleToIntConverter), NullValueHandling.Ignore)]`

or

Change the converter. 

I believe that the latter would a better appraoch.  The simplest implementation would be:

```
public class DoubleToIntConverter : JsonConverter<int>
{
  public override void WriteJson(JsonWriter? writer, int value, JsonSerializer serializer)
  {
    writer?.WriteValue(value);
  }

  public override int ReadJson(JsonReader? reader, Type objectType, int existingValue, bool hasExistingValue,
    JsonSerializer serializer)
  {
    return reader != null ? Convert.ToInt32(reader.Value, CultureInfo.InvariantCulture) : 0;
  }
}
```

**Comment by JohnnyCrazy** [comment]
AFAIK, `DurationMs` is not a `double`/`int` problem. It's encoded in an object, see discussion in #926

**Comment by Lewis-Fam** [comment]
I just tested my use of the api. I can confirm that the double to int works
for durationMs.

I removed double to int and it threw the serialization exception.

**Comment by JohnnyCrazy** [comment]
Do you have local tracks in the playlist? I think that's the only case where we see objects in the `durationMs` field.

**Comment by narutoshocker** [comment]
Hello,

Is this going to be merged soon or do we still have lingering issues?

**Comment by JohnnyCrazy** [comment]
Will be merged soonish, couple of days max, need to do some additional testing.

**Pull request merged**
