### PR TITLE
Possible fix for volume-control (#66)

### PR DESCRIPTION
**Pull request by JohnnyCrazy**
Could you guys check if this branch is working correctly? Don't have windows 10 on any machine sadly :cry:  #66 

@stuntguy3000
@JimmyAppelt (Thanks for the fix)

### CODE REVIEW

**Comment by stuntguy3000** [comment]
Only saw this now >.< testing.

**Comment by stuntguy3000** [comment]
Works a charm @JohnnyCrazy @JimmyAppelt

Cheers guys!

**Comment by stuntguy3000** [comment]
On a related note, is there a way to change the sound output device?

**Comment by JimmyAppelt** [comment]
> is there a way to change the sound output device?
@stuntguy3000 not sure if that's a logic thing that a this library should do :)

**Comment by JohnnyCrazy** [comment]
@stuntguy3000 Nope, sadly this isn't easy. I'm using `Equalify Pro` for my private usage, but I don't think there is something free and currently.

**Comment by stuntguy3000** [comment]
Damn that sucks. I really wonder how Equalifty Pro works.

**Comment by JohnnyCrazy** [comment]
@stuntguy3000 It propably does some function hooking. I could imagine it is hooking some kind of WINAPI Function like `GetAudioDevice`. Also, it does some kind of memory pattern-search since it's working across versions which means memory-addresses are not hard-coded.

**Comment by stuntguy3000** [comment]
I will research into it properly, cheers.

**Comment by Mrnikbobjeff** [comment]
@stuntguy3000 @JohnnyCrazy There are UNDOCUMENTED COM interfaces for this, as answered here:
http://stackoverflow.com/questions/13054371/programmatically-switch-audio-devices-on-windows-7
I do not know whether or not this works on any platform, but from my work for the volume change api I would suppose that it is indeed platform-neutral. Nevertheless, if you want to implement it it would be up to you as I sadly can not put my time into this at the moment.

**Pull request merged**
