### PR TITLE
Add interfaces for tokens

### PR DESCRIPTION
**Pull request by timia2109**
In my mind it's useful that all TokenTypes (or AuthRequestResonses) have a base type.

That's useful for applications which use client credentials or user credentials for special actions.

So I include the following base types:
 - **IToken**: Basic token information
 - **IUserToken**: Tokens, which have scopes for an access to userdata
 - **IRenewableToken**: Tokens, that containing an RefreshToken property

PS: Sorry for the UpgradeLog.htm, I don't now what VS try to do.

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Sounds like a good idea 👍 :)

**Review by JohnnyCrazy — CHANGES_REQUESTED** [review]
One thing: Let's change the namespace to `SpotifyAPI.Web`, so we're in-line with the rest of the files in the folder/parent-folder.

**Comment by timia2109** [comment]
I'm on it!

**Comment by timia2109** [comment]
Done 😊

**Comment by JohnnyCrazy** [comment]
Thanks! :)

**Pull request merged**
