### PR TITLE
Audio -Analysis

### PR DESCRIPTION
**Pull request by o-litnon**
linked to
https://github.com/JohnnyCrazy/SpotifyAPI-NET/issues/446

### CODE REVIEW

**Comment by JohnnyCrazy** [comment]
Looks good, ty! 👍

**Comment by vandenbrakel** [comment]
Is this fix available on Nuget?

**Comment by JohnnyCrazy** [comment]
Not yet, will deploy a fix today!

**Comment by vandenbrakel** [comment]
Great thanks.

Op do 7 mei 2020 om 17:31 schreef Jonas Dellinger <notifications@github.com>

**Pull request merged**
